title: Title to URL
description: A tool to generate URLs from article titles
theme: Architect

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:year/:month/:day/:title/

permalink: /:title/

social:
  github_username: YIN-Renlong
